### ISSUE TITLE
give feedback when only one link on screen

### ISSUE THREAD

**Issue by blaenk** [noctuid/link-hint.el#11]
When there's only one link in view, an avy marker isn't shown or anything, so it's easy to think nothing actually happened. Maybe if a message gets printed at the bottom saying the link was copied? In the case of `link-hint-copy-link`, for example.

**Comment by noctuid** [comment]
Sure, that's a good idea. Do you think it makes more sense to always have it message or to only message when there is only one link? I guess I could add an option that would allow for those two or ever messaging.

**Comment by blaenk** [comment]
I think it would be nice if it always did it yeah.

**Comment by noctuid** [comment]
Thanks for the suggestion. It will also explicitly message if no links are found now.

**Comment by blaenk** [comment]
Oh yeah that's perhaps even more important and I forgot to mention it. Good call!

**Comment by blaenk** [comment]
I just realized that it would be nice if the message would display the link that was acted upon, perhaps at the end, so that not only would you get confirmation that it happened, but that you didn't fat-finger the avvy shortcut, i.e. you can see at a glance that you did choose the correct link. I know I would personally love to have that safeguard.

Something like:

    Copied http://www.google.com

Or for opened links:

    Opening http://www.google.com

What do you think?

This is similar to what gist.el does when you post a gist, although I think it would be far more useful here.

For the ones that operate on multiple links, we can keep the current "on %d links" or something.

**Comment by noctuid** [comment]
I was thinking about doing that. I'll also change the messages to be simpler/clearer for the copy/open actions. Messaging for the open action isn't nearly as useful; for non-copyable links, I'll probably have the message stay the same since there is no url to message.

**Comment by blaenk** [comment]
Sounds good.

**Comment by noctuid** [comment]
Okay, I've implemented your suggestion. It should be working, but I didn't get a chance to test it extensively, so let me know if you find any problems or have any other suggestions.
