### ISSUE TITLE
link-hint-open multiple-links freezes Emacs when called on page with less than two links

### ISSUE THREAD

**Issue by jonasws** [noctuid/link-hint.el#13]
Hi!

I'm running Emacs 25.1.1, with the latest distribution of Spacemacs.

I am running into errors with opening multiple links: If the function is called and there is one or zero links on the page, Emacs becomes unresponsive.

I am not very proficient in Elisp programming (yet), but my guess is that it may have something to do with the behavior of the `interactive` function, it expecting some type of return value or such, and halts the program forever as nothing is ever returned to it. Can someone take a look at this?

Thanks for a cool package btw!

**Comment by noctuid** [comment]
Yeah, this package needs some work. I'll look into this soon.

**Comment by noctuid** [comment]
It should be fixed. The problem was an infinite loop caused by the collection function returning `t` when there weren't enough links. Thanks for reporting. Let me know if you encounter any other problems.

**Comment by jonasws** [comment]
Works great for me now after upgrading. Thanks for looking into it this quickly!
