### ISSUE TITLE
A closing parenthesis right after a url, gets included in the url

### ISSUE THREAD

**Issue by duianto** [noctuid/link-hint.el#15]
### Description
A closing parenthesis right after a url gets included in the url.

### Steps to reproduce
1. Start Emacs (with the `link-hint` package installed).
2. Open a new buffer: Press: `C-x b` Type: `new` Press: `RET`.
3. Type or copy and paste this url: `(url: https://google.com)` into the `new` buffer.
(it probably works with any url that ends with a parenthesis).
4. Move the cursor to the `h` in `https`.
5. Press: `M-x` Type: `link-hint-open-link` Press: `RET`

### Observed behaviour
The Emacs minibuffer shows: `Symbol's function definition is void: caddr`
and the address bar in the default browser (chrome) shows: `https://google.com%29/`
The page shows:
> This site can’t be reached
> 
> google.com%29’s server DNS address could not be found.
> Try running Windows Network Diagnostics.
> DNS_PROBE_FINISHED_NXDOMAIN

#### After step 4 if one instead runs this command:
`M-x` `link-hint-copy-link` `RET`
Then the minibuffer shows the same message: `Symbol's function definition is void: caddr`
and now the clipboard contains: `https://google.com)`

### System info
Windows 10 1607 (OS Build 14393.693)
GNU Emacs 25.1.1 (x86_64-w64-mingw32) of 2016-09-17
avy-20170208.148
link-hint-20161216.857

**Comment by noctuid** [comment]
This is a bug in `url-util.el`, which is the library that is currently used to get urls for generic modes (note that this works correctly, for example, in org mode). An alternative is `thing-at-point-url-at-point` (used by `goto-address.el`/`browse-url.el`/`ffap.el`), but it also has this bug.

I'll have to look into using something else.

**Comment by jb55** [comment]
every markdown link is broken :( any workarounds?

**Comment by noctuid** [comment]
I added an option (defaults to true) for now that will manually remove the paren as a workaround.

**Comment by jb55** [comment]
awesome! thank you!

**Comment by noctuid** [comment]
Thanks, I didn't realize string-trim-right had been changed. I updated it, so it should work now.

**Comment by ztlevi** [comment]
Is there a way that processes the left parenthesis as well? When I open link in `markdown-mode`, I cannot find any links. 😂

**Comment by noctuid** [comment]
@ztlevi Support for markdown links is now implemented on the development branch.

**Comment by ztlevi** [comment]
Sounds good! Thanks.

**Comment by jb55** [comment]
this looks fixed now? I think this can be closed.
