### ISSUE TITLE
`link-hint-open-link-at-point` on a web url after the first letter, asks for ftp password

### ISSUE THREAD

**Issue by duianto** [noctuid/link-hint.el#16]
### Description
When `link-hint-open-link-at-point` is called with the cursor on any other letter in a url than the first, then a prompt appears that asks for: `Password for (computer name)@https:`.

### Steps to reproduce
1. Start Emacs (with the `link-hint` package installed).
2. Open a new buffer: Press: `C-x b` Type: `new` Press: `RET`.
3. Type or copy and paste this url: `https://google.com` into the `new` buffer.
4. Move the cursor to any letter in the url **after** the first letter: `h`.
5. Press: `M-x` Type: `link-hint-open-link-at-point` Press: `RET`

### Observed behaviour
The Emacs minibuffer shows: 
`Password for (computer name)@https:`

If one just presses: `RET` then the minibuffer shows: `opening FTP connection to https...` for maybe two or three seconds, then a ``*ftp (computer name)@https*`` buffer opens, with the text:
```
Invalid help command foo.
open https
Unknown host https.
```
And this text: `(Internal Ange-ftp: no process)` is shown on the modeline.

### System info
Windows 10 1607 (OS Build 14393.693)
GNU Emacs 25.1.1 (x86_64-w64-mingw32) of 2016-09-17
avy-20170208.148
link-hint-20161216.857

**Comment by noctuid** [comment]
Thank you for all the detailed reports. This and #17 should be fixed now.

**Comment by duianto** [comment]
I doubt this is a normal occurrence, but if a backslash is in front of a url then it asks for an ftp password again. `\https://google.com`, with any of the `link-hint-(open/copy)-link(-at-point)` commands.

**Comment by noctuid** [comment]
I can't replicate this behavior. What does `(url-get-url-at-point)` return for you at that location? For me, it returns the correct url.

**Comment by duianto** [comment]
`S-M-;` (the Eval: prompt) and the command: `(url-get-url-at-point)` shows this.

With this url: `\https://google.com` and the cursor:
*  on the backslash `\` or after the url `C-e`, shows `nil`.
*  on the url, shows: `"https://google.com"`.

I re-tested with the `link-hint-*` commands in both Emacs with just the `link-hint` package installed, and in the Spacemacs on develop branch with the latest commit, and the `Password for (computer name)@https:` prompt appears with both configurations.

**Comment by noctuid** [comment]
That's what I would expect (it should work on the url but not on the backslash). Have you changed `link-hint-url-regexp` (could you post the value)?

This should return the url (and not nil):
```elisp
(let ((url (url-get-url-at-point)))
             (and url
                  (string-match link-hint-url-regexp url)
                  (match-string 0 url)))
```

If it works normally without the backslash, I can't imagine the string-match failing, so I'm really not sure what's happening.

To explain why it's asking for a password, for some reason things fall back to ffap for you. I may make some restrictions on when ffap is used in the future if it turns out to cause problems, but in cases where there is a legitimate url, ffap should never be called. It has the lowest precedence.

**Comment by duianto** [comment]
`C-h v link-hint-url-regexp` shows this:
```
link-hint-url-regexp is a variable defined in ‘link-hint.el’.
Its value is
"\\<\\(aaa://\\|about:\\|acap://\\|apt:\\|bzr://\\|bzr+ssh://\\|attachment:/\\|chrome://\\|cid:\\|content://\\|crid://\\|cvs://\\|dav:\\|dict://\\|doi:\\|dns:\\|dtn:\\|feed:\\|file:/\\|finger://\\|fish://\\|ftp://\\|geo:\\|git://\\|go:\\|gopher://\\|h323:\\|http://\\|https://\\|im:\\|imap://\\|info:\\|ipp:\\|irc://\\|irc6://\\|ircs://\\|iris.beep:\\|jar:\\|ldap://\\|ldaps://\\|magnet:\\|mid:\\|mtqp://\\|mupdate://\\|news:\\|nfs://\\|nntp://\\|opaquelocktoken:\\|pop://\\|pres:\\|resource://\\|rmi://\\|rsync://\\|rtsp://\\|rtspu://\\|service:\\|sftp://\\|sip:\\|sips:\\|smb://\\|sms:\\|snmp://\\|soap.beep://\\|soap.beeps://\\|ssh://\\|svn://\\|svn+ssh://\\|tag:\\|tel:\\|telnet://\\|tftp://\\|tip://\\|tn3270://\\|udp://\\|urn:\\|uuid:\\|vemmi://\\|webcal://\\|xri://\\|xmlrpc.beep://\\|xmlrpc.beeps://\\|z39.50r://\\|z39.50s://\\|xmpp:\\|fax:\\|man:\\|mms://\\|mmsh://\\|modem:\\|prospero:\\|snews:\\|wais://\\)[^]	\n \"'<>[^`{}]*[^]	\n \"'<>[^`{}.,;]+"

Documentation:
Regexp used to determine what constitutes a text url.
Defaults to ‘goto-address-url-regxp’. Note that this is used for text urls in
modes that don’t have some mechanism for supporting urls. This won’t affect
link-hint’s behavior in ‘org-mode’, for example.

You can customize this variable.
```
I haven't made any modifications. I'm just using this version of Emacs: `emacs-w64-25.1-O2.7z`, it was downloaded from here: https://github.com/zklhp/emacs-w64/releases , and I have only installed the
`link-hint` package.

To make sure that it wasn't an issue with the "optimizations" in that Emacs version, i also tested with the 3 https://www.gnu.org/software/emacs/ versions that i have:
emacs-24.5-bin-i686-mingw32
emacs-25.1-2-i686-w64-mingw32
emacs-25.1-i686-w64-mingw32

All versions have the same result as is discussed above.

**Comment by noctuid** [comment]
I was never able to replicate this with `url-get-url-at-point` or `(thing-at-point 'url)`. Since this seems like an unlikely case, and if there's an issue, it's with `url-util`, I'm going to go ahead and close this.
