### ISSUE TITLE
`link-hint-copy-link-at-point` shifts one slash in a url to the start

### ISSUE THREAD

**Issue by duianto** [noctuid/link-hint.el#17]
### Description
When `link-hint-copy-link-at-point` is called with the cursor on any other letter in a url than the first, then the url gets copied to the clipboard but, one of the double slashes has moved to the start of the url.

### Steps to reproduce
1. Start Emacs (with the `link-hint` package installed).
2. Open a new buffer: Press: `C-x b` Type: `new` Press: `RET`.
3. Type or copy and paste this url: `https://google.com` into the `new` buffer.
4. Move the cursor to any letter in the url **after** the first letter `h`.
5. Press: `M-x` Type: `link-hint-copy-link-at-point` Press: `RET`

### Observed behaviour
The clipboard now contains:
`/https:/google.com`

### System info
Windows 10 1607 (OS Build 14393.693)
GNU Emacs 25.1.1 (x86_64-w64-mingw32) of 2016-09-17
avy-20170208.148
link-hint-20161216.857

**Comment by duianto** [comment]
The slash still gets shifted if there's anything written right before `http`, like this:
/thisisaurlhttps:/google.com

**Comment by noctuid** [comment]
It looks like `url-util.el` expects there to be nothing before the url, so it doesn't detect anything at the point. It then falls through to `ffap` which messes up the url. It looks like `thing-at-point` doesn't have this problem, so I'll probably switch to using it.

**Comment by noctuid** [comment]
The paren case (which is definitely a legitimate issue) is handled correctly now since `thing-at-point` is used to check for a url first. The backslash case doesn't work by default, but the url regexp can be changed if anyone wants this case to work.
