### ISSUE TITLE
`link-hint-(open/copy)-link-at-point` on a single letter opens or copies a file path

### ISSUE THREAD

**Issue by duianto** [noctuid/link-hint.el#18]
### Description
When `link-hint-open-link-at-point` or `link-hint-copy-link-at-point` is called with the cursor on a single letter, and there is a single file that starts with that letter in the emacs/bin folder. Then that file opens as a new buffer or it's path gets copied to the clipboard.

### Steps to reproduce
1. Start Emacs (with the `link-hint` package installed).
2. Open a new buffer: Press: `C-x b` Type: `new` Press: `RET`.
3. Type a letter, for example: `a` into the `new` buffer.
4. Move the cursor ontop of the `a` or one position to the right of it.
5. Press: `M-x` Type: `link-hint-open-link-at-point` Press: `RET`

### Observed behaviour
The `addpm.exe` file opens in a new buffer.

#### After step 4 if one instead calls the command
`link-hint-copy-link-at-point`, then the clipboard contains the path: `../emacs-w64-25.1-O2/bin/addpm.exe`

It also works with `c`, `r` and `z`, but it doesn't work when there are several files that start with the same letter, for instance `e` or `l`, then the minibuffer shows: `There is no supported link at the point.`

### System info
Windows 10 1607 (OS Build 14393.693)
GNU Emacs 25.1.1 (x86_64-w64-mingw32) of 2016-09-17
avy-20170208.148
link-hint-20161216.857

**Comment by noctuid** [comment]
This is an issue with `ffap.el` (I pretty sure it's intentional to make things more convenient if you don't have the full name of a file in the buffer). I may look into adding a check afterwards to make sure the filename is exact. I'd probably add it as an option though. It seems unlikely to me that this would cause a legitimate problem (e.g. where a different type of link should be opened, not a file).

**Comment by duianto** [comment]
It might be working as expected, it was just something i noticed when i was making the reproduction steps for the closing parenthesis issue. This can probably be closed and if someone discovers an problem with how it currently works, then this issue could be reopened.

**Comment by noctuid** [comment]
I'll close this for now then. I can add change the behavior or add an option if someone finds this behavior to be a problem
