### ISSUE TITLE
Add org-roam link types

### ISSUE THREAD

**Issue by dit7ya** [noctuid/link-hint.el#180]
[Org-roam](https://www.orgroam.com/) links are just regular but renamed org links and currently link-hint does not work on them.

The following code works for me, if this seems fine I can start a PR.

```elisp

(link-hint-define-type 'org-roam-link
  :next #'link-hint--next-org-link
  :at-point-p #'link-hint--org-link-at-point-p
  :vars '(org-mode org-agenda-mode org-roam-mode org-link-minor-mode)
  :open #'link-hint--open-org-link
  :open-multiple t
  :copy #'kill-new)

```

**Comment by noctuid** [comment]
A PR would be welcome. I will get around to making the change otherwise.

**Comment by dit7ya** [comment]
This was a false issue, so I am closing it.

**Comment by mohkale** [comment]
@noctuid 

This is now relevent again. Org-roam v2 added a dedicated org-roam-mode for use in special link buffers. These buffers have several org-mode links.
