### ISSUE TITLE
Doesn't work when using gnus-w3m to render e-mails

### ISSUE THREAD

**Issue by jwiegley** [noctuid/link-hint.el#21]
The command `widget-button-press` works for visiting links in HTML e-mails, but `push-button` raises an exception about the action being `nil`.

**Comment by noctuid** [comment]
Is this issue present on the `develop` branch? I haven't used `gnus-w3m`, but it should be simple to add a new link type for it if necessary.

**Comment by jwiegley** [comment]
I haven't tried the `develop` branch.

**Comment by noctuid** [comment]
I've added support for the two link types I found when looking through emails in my maildir. I've never used gnus before today, so please let me if you have any issues (e.g. there are other types of links I missed or `gnus-article-mode` is not the only mode where these links can exist).

**Comment by tshu-w** [comment]
cannot use in mu4e mail either.

```
Debugger entered--Lisp error: (args-out-of-range 1 1315)
  text-property-any(1 1315 invisible nil)
  link-hint--find-property-with-value(invisible nil 1 nil)
  link-hint--find-property(invisible 1 nil)
  link-hint--next-property(invisible)
  link-hint--find-visible-regions(1 1309)
  link-hint--collect-visible-links()
  link-hint--get-links()
  link-hint--one(:open)
  link-hint-open-link()
  funcall-interactively(link-hint-open-link)
  call-interactively(link-hint-open-link nil nil)
  command-execute(link-hint-open-link)
```
