### ISSUE TITLE
link-hint.el must start with three semi-colons rather than two

### ISSUE THREAD

**Issue by emacs18** [noctuid/link-hint.el#22]
When I tried to build link-hint package myself using quelpa, it failed, because the first line of the file has only two semi-colons rather than three.   See package-buffer-info function in package.el for the regexp that expects three semi-colons.  All other packages that I examined all start with three semi-colons.

I could have submitted a PR, but I don't do that often enough that it is a pain for me to refresh my memory on how to do that.  Sorry.

**Comment by noctuid** [comment]
Thanks for reporting. I might not have ever noticed this issue otherwise. It looks like the format was correct for the initial commit and somewhere down the line I accidentally deleted a semicolon.
