### ISSUE TITLE
Use org-open-at-point?

### ISSUE THREAD

**Issue by fandag** [noctuid/link-hint.el#4]
Would it make sense to use `org-open-at-point` instead of `browse-url` for link of type `htmlize-url`? I would like to open different org link types with the appropriate program, e.g. "mu4e:" links with mu4e instead of the system browser.

**Comment by noctuid** [comment]
Does it currently try to open mu4e links in the browser? I'll add a new link type or change `htmlize-url` to `org-url` and have it open "file:", heading, "mu4e:", etc. links as well.

**Comment by noctuid** [comment]
Alright, mu4e links (and any other org links) should work now. I made a separate issue (#6) for the bug I mentioned above.

**Comment by fandag** [comment]
Great, thanks for the very quick feedback! I'll test it the upcoming days and see if I hit the issue you mention.
