### ISSUE TITLE
Feature request: support org agenda

### ISSUE THREAD

**Issue by PhilHudson** [noctuid/link-hint.el#45]
I can't figure out what is needed to make `link-hint` detect links in the Org agenda. The very same links are detected correctly in their originating Org files when those individual files' buffers are selected rather than the agenda which collates them. The same command `org-next-link` works in either, which suggests to me that you don't/shouldn't need an agenda-mode-aware version.

**Comment by noctuid** [comment]
Try it now.

**Comment by PhilHudson** [comment]
Thanks for such a swift turnaround!
