### ISSUE TITLE
output warnings after loading emacs with link-hint

### ISSUE THREAD

**Issue by muralikodali** [noctuid/link-hint.el#49]
reloading emacs after installing link-hint.el gave following warnings :  

```sh
In link-hint--text-url-at-point-p:
link-hint.el:294:19:Warning: ‘url-get-url-at-point’ is an obsolete function
    (as of 27.1); use ‘thing-at-point-url-at-point’ instead.

In end of data:
link-hint.el:1261:1:Warning: the following functions are not known to be
    defined: package-desc-extras, package-desc-name

```

**Comment by akirak** [comment]
They are just warnings, so you can continue using this package.

You can vanish the second warnings by adding the following code:

```emacs-lisp
(declare-function package-desc-name "ext:package")
(declare-function package-desc-extras "ext:package")
```

**Comment by muralikodali** [comment]
thanks for your suggestion

**Comment by noctuid** [comment]
I've added the `declare-function`s. It may not be possible to address the first warning. Last time I checked, `thing-at-point-url-at-point` was not suitable, and I was intentionally using `url-get-url-at-point`.
